/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnulerRouteImport } from './routes/annuler'
import { Route as ContactezNousRouteImport } from './routes/contactez-nous'
import { Route as FormulesRouteImport } from './routes/formules'
import { Route as NettoyageAutoADomicileToulouseRouteImport } from './routes/nettoyage-auto-a-domicile-toulouse'
import { Route as NettoyageCanapeToulouseRouteImport } from './routes/nettoyage-canape-toulouse'
import { Route as NettoyageDappartementOuMaisonRouteImport } from './routes/nettoyage-dappartement-ou-maison'
import { Route as NettoyageDeFinDeChantierToulouseRouteImport } from './routes/nettoyage-de-fin-de-chantier-toulouse'
import { Route as NettoyageDeVitresToulouseRouteImport } from './routes/nettoyage-de-vitres-toulouse'
import { Route as NettoyageDiogeneToulouseRouteImport } from './routes/nettoyage-diogene-toulouse'
import { Route as NettoyageExtremeToulouseRouteImport } from './routes/nettoyage-extreme-toulouse'
import { Route as NettoyageFacadeToulouseRouteImport } from './routes/nettoyage-facade-toulouse'
import { Route as NettoyageFinDeBailToulouseRouteImport } from './routes/nettoyage-fin-de-bail-toulouse'
import { Route as NettoyageMatelasToulouseRouteImport } from './routes/nettoyage-matelas-toulouse'
import { Route as NettoyageTapisToulouseRouteImport } from './routes/nettoyage-tapis-toulouse'
import { Route as NettoyageTerrasseToulouseRouteImport } from './routes/nettoyage-terrasse-toulouse'
import { Route as NettoyageToitureToulouseRouteImport } from './routes/nettoyage-toiture-toulouse'
import { Route as NosRealisationsRouteImport } from './routes/nos-realisations'
import { Route as NosServicesRouteImport } from './routes/nos-services'
import { Route as ReserverRouteImport } from './routes/reserver'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnulerRoute = AnnulerRouteImport.update({
  id: '/annuler',
  path: '/annuler',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactezNousRoute = ContactezNousRouteImport.update({
  id: '/contactez-nous',
  path: '/contactez-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulesRoute = FormulesRouteImport.update({
  id: '/formules',
  path: '/formules',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageAutoADomicileToulouseRoute =
  NettoyageAutoADomicileToulouseRouteImport.update({
    id: '/nettoyage-auto-a-domicile-toulouse',
    path: '/nettoyage-auto-a-domicile-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageCanapeToulouseRoute = NettoyageCanapeToulouseRouteImport.update({
  id: '/nettoyage-canape-toulouse',
  path: '/nettoyage-canape-toulouse',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageDappartementOuMaisonRoute =
  NettoyageDappartementOuMaisonRouteImport.update({
    id: '/nettoyage-dappartement-ou-maison',
    path: '/nettoyage-dappartement-ou-maison',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageDeFinDeChantierToulouseRoute =
  NettoyageDeFinDeChantierToulouseRouteImport.update({
    id: '/nettoyage-de-fin-de-chantier-toulouse',
    path: '/nettoyage-de-fin-de-chantier-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageDeVitresToulouseRoute =
  NettoyageDeVitresToulouseRouteImport.update({
    id: '/nettoyage-de-vitres-toulouse',
    path: '/nettoyage-de-vitres-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageDiogeneToulouseRoute =
  NettoyageDiogeneToulouseRouteImport.update({
    id: '/nettoyage-diogene-toulouse',
    path: '/nettoyage-diogene-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageExtremeToulouseRoute =
  NettoyageExtremeToulouseRouteImport.update({
    id: '/nettoyage-extreme-toulouse',
    path: '/nettoyage-extreme-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageFacadeToulouseRoute = NettoyageFacadeToulouseRouteImport.update({
  id: '/nettoyage-facade-toulouse',
  path: '/nettoyage-facade-toulouse',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageFinDeBailToulouseRoute =
  NettoyageFinDeBailToulouseRouteImport.update({
    id: '/nettoyage-fin-de-bail-toulouse',
    path: '/nettoyage-fin-de-bail-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageMatelasToulouseRoute =
  NettoyageMatelasToulouseRouteImport.update({
    id: '/nettoyage-matelas-toulouse',
    path: '/nettoyage-matelas-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageTapisToulouseRoute = NettoyageTapisToulouseRouteImport.update({
  id: '/nettoyage-tapis-toulouse',
  path: '/nettoyage-tapis-toulouse',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageTerrasseToulouseRoute =
  NettoyageTerrasseToulouseRouteImport.update({
    id: '/nettoyage-terrasse-toulouse',
    path: '/nettoyage-terrasse-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NettoyageToitureToulouseRoute =
  NettoyageToitureToulouseRouteImport.update({
    id: '/nettoyage-toiture-toulouse',
    path: '/nettoyage-toiture-toulouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const NosRealisationsRoute = NosRealisationsRouteImport.update({
  id: '/nos-realisations',
  path: '/nos-realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const NosServicesRoute = NosServicesRouteImport.update({
  id: '/nos-services',
  path: '/nos-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annuler': typeof AnnulerRoute
  '/contactez-nous': typeof ContactezNousRoute
  '/formules': typeof FormulesRoute
  '/nettoyage-auto-a-domicile-toulouse': typeof NettoyageAutoADomicileToulouseRoute
  '/nettoyage-canape-toulouse': typeof NettoyageCanapeToulouseRoute
  '/nettoyage-dappartement-ou-maison': typeof NettoyageDappartementOuMaisonRoute
  '/nettoyage-de-fin-de-chantier-toulouse': typeof NettoyageDeFinDeChantierToulouseRoute
  '/nettoyage-de-vitres-toulouse': typeof NettoyageDeVitresToulouseRoute
  '/nettoyage-diogene-toulouse': typeof NettoyageDiogeneToulouseRoute
  '/nettoyage-extreme-toulouse': typeof NettoyageExtremeToulouseRoute
  '/nettoyage-facade-toulouse': typeof NettoyageFacadeToulouseRoute
  '/nettoyage-fin-de-bail-toulouse': typeof NettoyageFinDeBailToulouseRoute
  '/nettoyage-matelas-toulouse': typeof NettoyageMatelasToulouseRoute
  '/nettoyage-tapis-toulouse': typeof NettoyageTapisToulouseRoute
  '/nettoyage-terrasse-toulouse': typeof NettoyageTerrasseToulouseRoute
  '/nettoyage-toiture-toulouse': typeof NettoyageToitureToulouseRoute
  '/nos-realisations': typeof NosRealisationsRoute
  '/nos-services': typeof NosServicesRoute
  '/reserver': typeof ReserverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annuler': typeof AnnulerRoute
  '/contactez-nous': typeof ContactezNousRoute
  '/formules': typeof FormulesRoute
  '/nettoyage-auto-a-domicile-toulouse': typeof NettoyageAutoADomicileToulouseRoute
  '/nettoyage-canape-toulouse': typeof NettoyageCanapeToulouseRoute
  '/nettoyage-dappartement-ou-maison': typeof NettoyageDappartementOuMaisonRoute
  '/nettoyage-de-fin-de-chantier-toulouse': typeof NettoyageDeFinDeChantierToulouseRoute
  '/nettoyage-de-vitres-toulouse': typeof NettoyageDeVitresToulouseRoute
  '/nettoyage-diogene-toulouse': typeof NettoyageDiogeneToulouseRoute
  '/nettoyage-extreme-toulouse': typeof NettoyageExtremeToulouseRoute
  '/nettoyage-facade-toulouse': typeof NettoyageFacadeToulouseRoute
  '/nettoyage-fin-de-bail-toulouse': typeof NettoyageFinDeBailToulouseRoute
  '/nettoyage-matelas-toulouse': typeof NettoyageMatelasToulouseRoute
  '/nettoyage-tapis-toulouse': typeof NettoyageTapisToulouseRoute
  '/nettoyage-terrasse-toulouse': typeof NettoyageTerrasseToulouseRoute
  '/nettoyage-toiture-toulouse': typeof NettoyageToitureToulouseRoute
  '/nos-realisations': typeof NosRealisationsRoute
  '/nos-services': typeof NosServicesRoute
  '/reserver': typeof ReserverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annuler': typeof AnnulerRoute
  '/contactez-nous': typeof ContactezNousRoute
  '/formules': typeof FormulesRoute
  '/nettoyage-auto-a-domicile-toulouse': typeof NettoyageAutoADomicileToulouseRoute
  '/nettoyage-canape-toulouse': typeof NettoyageCanapeToulouseRoute
  '/nettoyage-dappartement-ou-maison': typeof NettoyageDappartementOuMaisonRoute
  '/nettoyage-de-fin-de-chantier-toulouse': typeof NettoyageDeFinDeChantierToulouseRoute
  '/nettoyage-de-vitres-toulouse': typeof NettoyageDeVitresToulouseRoute
  '/nettoyage-diogene-toulouse': typeof NettoyageDiogeneToulouseRoute
  '/nettoyage-extreme-toulouse': typeof NettoyageExtremeToulouseRoute
  '/nettoyage-facade-toulouse': typeof NettoyageFacadeToulouseRoute
  '/nettoyage-fin-de-bail-toulouse': typeof NettoyageFinDeBailToulouseRoute
  '/nettoyage-matelas-toulouse': typeof NettoyageMatelasToulouseRoute
  '/nettoyage-tapis-toulouse': typeof NettoyageTapisToulouseRoute
  '/nettoyage-terrasse-toulouse': typeof NettoyageTerrasseToulouseRoute
  '/nettoyage-toiture-toulouse': typeof NettoyageToitureToulouseRoute
  '/nos-realisations': typeof NosRealisationsRoute
  '/nos-services': typeof NosServicesRoute
  '/reserver': typeof ReserverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annuler'
    | '/contactez-nous'
    | '/formules'
    | '/nettoyage-auto-a-domicile-toulouse'
    | '/nettoyage-canape-toulouse'
    | '/nettoyage-dappartement-ou-maison'
    | '/nettoyage-de-fin-de-chantier-toulouse'
    | '/nettoyage-de-vitres-toulouse'
    | '/nettoyage-diogene-toulouse'
    | '/nettoyage-extreme-toulouse'
    | '/nettoyage-facade-toulouse'
    | '/nettoyage-fin-de-bail-toulouse'
    | '/nettoyage-matelas-toulouse'
    | '/nettoyage-tapis-toulouse'
    | '/nettoyage-terrasse-toulouse'
    | '/nettoyage-toiture-toulouse'
    | '/nos-realisations'
    | '/nos-services'
    | '/reserver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annuler'
    | '/contactez-nous'
    | '/formules'
    | '/nettoyage-auto-a-domicile-toulouse'
    | '/nettoyage-canape-toulouse'
    | '/nettoyage-dappartement-ou-maison'
    | '/nettoyage-de-fin-de-chantier-toulouse'
    | '/nettoyage-de-vitres-toulouse'
    | '/nettoyage-diogene-toulouse'
    | '/nettoyage-extreme-toulouse'
    | '/nettoyage-facade-toulouse'
    | '/nettoyage-fin-de-bail-toulouse'
    | '/nettoyage-matelas-toulouse'
    | '/nettoyage-tapis-toulouse'
    | '/nettoyage-terrasse-toulouse'
    | '/nettoyage-toiture-toulouse'
    | '/nos-realisations'
    | '/nos-services'
    | '/reserver'
  id:
    | '__root__'
    | '/'
    | '/annuler'
    | '/contactez-nous'
    | '/formules'
    | '/nettoyage-auto-a-domicile-toulouse'
    | '/nettoyage-canape-toulouse'
    | '/nettoyage-dappartement-ou-maison'
    | '/nettoyage-de-fin-de-chantier-toulouse'
    | '/nettoyage-de-vitres-toulouse'
    | '/nettoyage-diogene-toulouse'
    | '/nettoyage-extreme-toulouse'
    | '/nettoyage-facade-toulouse'
    | '/nettoyage-fin-de-bail-toulouse'
    | '/nettoyage-matelas-toulouse'
    | '/nettoyage-tapis-toulouse'
    | '/nettoyage-terrasse-toulouse'
    | '/nettoyage-toiture-toulouse'
    | '/nos-realisations'
    | '/nos-services'
    | '/reserver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnulerRoute: typeof AnnulerRoute
  ContactezNousRoute: typeof ContactezNousRoute
  FormulesRoute: typeof FormulesRoute
  NettoyageAutoADomicileToulouseRoute: typeof NettoyageAutoADomicileToulouseRoute
  NettoyageCanapeToulouseRoute: typeof NettoyageCanapeToulouseRoute
  NettoyageDappartementOuMaisonRoute: typeof NettoyageDappartementOuMaisonRoute
  NettoyageDeFinDeChantierToulouseRoute: typeof NettoyageDeFinDeChantierToulouseRoute
  NettoyageDeVitresToulouseRoute: typeof NettoyageDeVitresToulouseRoute
  NettoyageDiogeneToulouseRoute: typeof NettoyageDiogeneToulouseRoute
  NettoyageExtremeToulouseRoute: typeof NettoyageExtremeToulouseRoute
  NettoyageFacadeToulouseRoute: typeof NettoyageFacadeToulouseRoute
  NettoyageFinDeBailToulouseRoute: typeof NettoyageFinDeBailToulouseRoute
  NettoyageMatelasToulouseRoute: typeof NettoyageMatelasToulouseRoute
  NettoyageTapisToulouseRoute: typeof NettoyageTapisToulouseRoute
  NettoyageTerrasseToulouseRoute: typeof NettoyageTerrasseToulouseRoute
  NettoyageToitureToulouseRoute: typeof NettoyageToitureToulouseRoute
  NosRealisationsRoute: typeof NosRealisationsRoute
  NosServicesRoute: typeof NosServicesRoute
  ReserverRoute: typeof ReserverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuler': {
      id: '/annuler'
      path: '/annuler'
      fullPath: '/annuler'
      preLoaderRoute: typeof AnnulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactez-nous': {
      id: '/contactez-nous'
      path: '/contactez-nous'
      fullPath: '/contactez-nous'
      preLoaderRoute: typeof ContactezNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formules': {
      id: '/formules'
      path: '/formules'
      fullPath: '/formules'
      preLoaderRoute: typeof FormulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-auto-a-domicile-toulouse': {
      id: '/nettoyage-auto-a-domicile-toulouse'
      path: '/nettoyage-auto-a-domicile-toulouse'
      fullPath: '/nettoyage-auto-a-domicile-toulouse'
      preLoaderRoute: typeof NettoyageAutoADomicileToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-canape-toulouse': {
      id: '/nettoyage-canape-toulouse'
      path: '/nettoyage-canape-toulouse'
      fullPath: '/nettoyage-canape-toulouse'
      preLoaderRoute: typeof NettoyageCanapeToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-dappartement-ou-maison': {
      id: '/nettoyage-dappartement-ou-maison'
      path: '/nettoyage-dappartement-ou-maison'
      fullPath: '/nettoyage-dappartement-ou-maison'
      preLoaderRoute: typeof NettoyageDappartementOuMaisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-de-fin-de-chantier-toulouse': {
      id: '/nettoyage-de-fin-de-chantier-toulouse'
      path: '/nettoyage-de-fin-de-chantier-toulouse'
      fullPath: '/nettoyage-de-fin-de-chantier-toulouse'
      preLoaderRoute: typeof NettoyageDeFinDeChantierToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-de-vitres-toulouse': {
      id: '/nettoyage-de-vitres-toulouse'
      path: '/nettoyage-de-vitres-toulouse'
      fullPath: '/nettoyage-de-vitres-toulouse'
      preLoaderRoute: typeof NettoyageDeVitresToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-diogene-toulouse': {
      id: '/nettoyage-diogene-toulouse'
      path: '/nettoyage-diogene-toulouse'
      fullPath: '/nettoyage-diogene-toulouse'
      preLoaderRoute: typeof NettoyageDiogeneToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-extreme-toulouse': {
      id: '/nettoyage-extreme-toulouse'
      path: '/nettoyage-extreme-toulouse'
      fullPath: '/nettoyage-extreme-toulouse'
      preLoaderRoute: typeof NettoyageExtremeToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-facade-toulouse': {
      id: '/nettoyage-facade-toulouse'
      path: '/nettoyage-facade-toulouse'
      fullPath: '/nettoyage-facade-toulouse'
      preLoaderRoute: typeof NettoyageFacadeToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-fin-de-bail-toulouse': {
      id: '/nettoyage-fin-de-bail-toulouse'
      path: '/nettoyage-fin-de-bail-toulouse'
      fullPath: '/nettoyage-fin-de-bail-toulouse'
      preLoaderRoute: typeof NettoyageFinDeBailToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-matelas-toulouse': {
      id: '/nettoyage-matelas-toulouse'
      path: '/nettoyage-matelas-toulouse'
      fullPath: '/nettoyage-matelas-toulouse'
      preLoaderRoute: typeof NettoyageMatelasToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-tapis-toulouse': {
      id: '/nettoyage-tapis-toulouse'
      path: '/nettoyage-tapis-toulouse'
      fullPath: '/nettoyage-tapis-toulouse'
      preLoaderRoute: typeof NettoyageTapisToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-terrasse-toulouse': {
      id: '/nettoyage-terrasse-toulouse'
      path: '/nettoyage-terrasse-toulouse'
      fullPath: '/nettoyage-terrasse-toulouse'
      preLoaderRoute: typeof NettoyageTerrasseToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-toiture-toulouse': {
      id: '/nettoyage-toiture-toulouse'
      path: '/nettoyage-toiture-toulouse'
      fullPath: '/nettoyage-toiture-toulouse'
      preLoaderRoute: typeof NettoyageToitureToulouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-realisations': {
      id: '/nos-realisations'
      path: '/nos-realisations'
      fullPath: '/nos-realisations'
      preLoaderRoute: typeof NosRealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-services': {
      id: '/nos-services'
      path: '/nos-services'
      fullPath: '/nos-services'
      preLoaderRoute: typeof NosServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnulerRoute: AnnulerRoute,
  ContactezNousRoute: ContactezNousRoute,
  FormulesRoute: FormulesRoute,
  NettoyageAutoADomicileToulouseRoute: NettoyageAutoADomicileToulouseRoute,
  NettoyageCanapeToulouseRoute: NettoyageCanapeToulouseRoute,
  NettoyageDappartementOuMaisonRoute: NettoyageDappartementOuMaisonRoute,
  NettoyageDeFinDeChantierToulouseRoute: NettoyageDeFinDeChantierToulouseRoute,
  NettoyageDeVitresToulouseRoute: NettoyageDeVitresToulouseRoute,
  NettoyageDiogeneToulouseRoute: NettoyageDiogeneToulouseRoute,
  NettoyageExtremeToulouseRoute: NettoyageExtremeToulouseRoute,
  NettoyageFacadeToulouseRoute: NettoyageFacadeToulouseRoute,
  NettoyageFinDeBailToulouseRoute: NettoyageFinDeBailToulouseRoute,
  NettoyageMatelasToulouseRoute: NettoyageMatelasToulouseRoute,
  NettoyageTapisToulouseRoute: NettoyageTapisToulouseRoute,
  NettoyageTerrasseToulouseRoute: NettoyageTerrasseToulouseRoute,
  NettoyageToitureToulouseRoute: NettoyageToitureToulouseRoute,
  NosRealisationsRoute: NosRealisationsRoute,
  NosServicesRoute: NosServicesRoute,
  ReserverRoute: ReserverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
